version: "3"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: database_mysql
    ports:
      - 3306:3306
    env_file: 
      - db.env
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - mynetwork

  app:
    build: .
    container_name: "api"
    ports:
      - 4000:4000
    volumes:
      - .:/usr/app
    networks:
      - mynetwork

volumes:
  mysqldata:
    driver: local


networks:
  mynetwork:
    name: mynetwork